project:
  type: book
  output-dir: docs

book:
  title: "Modelos Estadísticos para la Predicción"
  author: "Víctor Aceña - Isaac Martín"
  date: last-modified
  search: true
  chapters:
    - index.qmd
    - tema0.qmd
    - tema1.qmd
    - tema2.qmd
    - tema3.qmd
    - tema4.qmd
    - tema5.qmd
    - conclusiones.qmd
    - references.qmd
  cover-image: DSLab_logo_2.png

bibliography: references.bib

format:
  html:
    theme: cerulean
    lang: es
    css: styles.css
  pdf:
    documentclass: scrreprt

editor: visual







